### ISSUE TITLE
Module build failed: Error: The style-loader cannot be used in a non-browser environment

### ISSUE THREAD

**Issue by wzup** [webpack-contrib/extract-text-webpack-plugin#151]
What error is this? How to resolve?

```
    module: {
        loaders: [{
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract(['style?insertAt=top&-singleton', 'css?sourceMap', 'sass?sourceMap'])
        }, {
            test: /\.jsx$/,
            loader: 'babel',
            query: {
                presets: ['react', 'es2015']
            },
        }]
    },
```

**Comment by tkirill** [comment]
@wzup This is because of `style-loader`.  I don't know exactly how the loader from `extract-text-webpack-plugin` works but I believe it effectively evaluates JS from the final loader and somehow extracts the CSS from result.

The final loader is `style-loader` in this case and it wants to add `<style>` tags in the `document`.  This is where the error occurs, I think.

The solution is to pass `style-loader` as `nonExtractLoader` in the first parameter:

    loader: ExtractTextPlugin.extract('style?insertAt=top&-singleton', ['css?sourceMap', 'sass?sourceMap']

If you don't use Code Split and chunks then you can just omit `style-loader` since it effectively does nothing in this case:

    loader: ExtractTextPlugin.extract(['css?sourceMap', 'sass?sourceMap']

**Comment by milworm** [comment]
Try to use this https://github.com/kriasoft/isomorphic-style-loader. Works good for me.
