### ISSUE TITLE
bug used with webpack.optimize.CommonsChunkPlugin

### ISSUE THREAD

**Issue by wenbing** [webpack-contrib/extract-text-webpack-plugin#185]
when used with webpack.optimize.CommonsChunkPlugin，there are some modules is missing,

![image](https://cloud.githubusercontent.com/assets/87431/15271668/1d4d0070-1a87-11e6-809b-7dc604d3940f.png)

you can see it in：
https://github.com/wenbing/webpack-extract-text-commons-chunk-bug

**Comment by medifle** [comment]
Same issue here.

Details about the test case above

```bash
rm -rf ./public/ && webpack --display-chunks --display-modules
![image](https://cloud.githubusercontent.com/assets/13296643/15382178/f5078802-1db9-11e6-8885-22d7a2a4d2f8.png)
```

If I comment out the `CommonsChunkPlugin` block

```javascript
/* eslint no-use-before-define:0 */
'use strict';
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './main.js',
  module: {
    loaders: [
      { test: /\.css$/, loaders: ['style-loader', 'css-loader'] },
      {
        test: /\.gss$/,
        loaders: ExtractTextPlugin.extract('style-loader', ['css-loader']).split('!'),
      },
    ],
  },
  plugins: [
    new ExtractTextPlugin('[name].css'),
    // new webpack.optimize.CommonsChunkPlugin({
    //   children: true,
    // }),
  ],
  output: {
    filename: '[name].js',
    path: __dirname + '/public',
    publicPath: 'public/',
  },
};
```

![image](https://cloud.githubusercontent.com/assets/13296643/15382918/3c9c018c-1dc1-11e6-8a5b-552f13393b43.png)

**Comment by theandrewchan** [comment]
I'm also having this issue, and I'm only using a single entry point with 2 chunks and very simple module dependencies.

**Comment by Kovensky** [comment]
The commons chunk will only have the common modules; the other modules are (supposed to be) in the other chunks, and they install themselves by calling the commons chunk's `webpackJsonp` when they are loaded.

Make sure you are including all the chunks in `<script>` tags, with the commons chunk being first.

**Comment by theandrewchan** [comment]
Are you sure including the split (non-entry) chunks in `<script>` tags is the solution? I thought the whole point of code splitting was so that the unneeded script chunks would only need to be _downloaded_ when necessary. If I include all the chunks in the entry html page, they all get downloaded anyway, which kind of defeats the point.

**Comment by evilebottnawi** [comment]
@wenbing @theandrewchan problem still exists?

**Comment by ravi-yadav-oyo** [comment]
@evilebottnawi  encountering this issue in webpack `3.2` moving to `3.10` solves it but also introduces another issue.

Basically i have a  dynamic entry chunk in react-router file.
but in webpack `3` am unable to extract the css into seperate chunks from these entry files.
so included the same chunknames in webpack entry.

Now the chunks are created and css without duplicates are extracted and common scss imports from multiple entry files is moved to the commonChunks entry But i start getting this error.
Maybe because i specify entry chunk twice now(1 in webpack entry and another time in react-router file)

So i upgraded to `3.10` it solved the issue but now the css chunks have duplicate css in them.

So wanted to know any solutions or alternatives to extract css in seperate named chunks in webpack `3.2` or solve the duplicate css issue in `3.10`

link to stackoverflow question
https://stackoverflow.com/questions/38905281/webpack-missing-modules-with-commonschunk-and-extract-text-webpack-plugin#

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
