### ISSUE TITLE
Remove empty module functions in bundle

### ISSUE THREAD

**Issue by 454de6e** [webpack-contrib/extract-text-webpack-plugin#229]
When using this plugin with `allChunks: true`, I get a number of empty module functions in the bundle:

```
function(module, exports) {

    // removed by extract-text-webpack-plugin

/***/ },
```

Is there a way to have webpack suppress/remove them to reduce the bloat?

**Comment by Kovensky** [comment]
It is possible to use the `query` field in the `loaders` entry where you extract to set `query.remove = true`, but that breaks css modules.

Maybe `query.remove` should remove the module _unless_ there are locals to export?

**Comment by mdotasia** [comment]
Is this documented anywhere?

**Comment by mblandfo** [comment]
It looks like remove: true is the default: https://github.com/webpack/extract-text-webpack-plugin/blob/webpack-1/index.js

So "remove" actually just leaves an empty stub in your bundle for every css file you included. I was planning to use the css loader in dev because hot module replacement is amazing, and switch to this extract text webpack plugin in prod since the docs said it's faster as a separate css file. But, if it's going to add a bunch of stubs I think I'll just use grunt to concat my css in prod.

**Comment by avesus** [comment]
Also see https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/489

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
