### ISSUE TITLE
Error when using with AggressiveSplittingPlugin 

### ISSUE THREAD

**Issue by mohsen1** [webpack-contrib/extract-text-webpack-plugin#323]
[I initially reported this issue at Webpak](https://github.com/webpack/webpack/issues/3525)

Today I spent a little time investigating this and found that issue is in this plugin. The loader is specifying a single output file name [`"extract-text-webpack-plugin-output-filename"`](https://github.com/webpack/extract-text-webpack-plugin/blob/8232a3e5c5c719c1a56228fed0c3d12a0c90eded/loader.js#L44) that results in conflicts .

~~I figured commenting out following [lines](https://github.com/webpack/extract-text-webpack-plugin/blob/8232a3e5c5c719c1a56228fed0c3d12a0c90eded/loader.js#L66-L69) fixes the issue:~~ [this isn't working actually]

**Comment by mohsen1** [comment]
I looked at this issue for a good amount of time. Not knowing Webpack internals I couldn't figure it out. I've made a test environment to try this out. Check out [my fork of this project ](https://github.com/mohsen1/extract-text-webpack-plugin)and [TravisCI outputs ](https://travis-ci.org/mohsen1/extract-text-webpack-plugin/jobs/189011333)

/cc @sokra @TheLarkInn

**Comment by CntChen** [comment]
After many days in reviewing and testing the source code of `AggressiveSplittingPlugin` and `extract-text-webpack-plugin`. The problem happened because:
* `extract-text-webpack-plugin` use `childCompiler` to extarct a CSS module and it's dependencies into independent chunk. 
* if CSS module independent chunk's size beyond `AggressiveSplittingPlugin` splitting threshold (`maxSize`), independent chunk will splitted into many smaller chunks.
* in `extract-text-webpack-plugin` childCompiler, the `output` webpack option set filename to `extract-text-webpack-plugin-output-filename`. And there more than one chunk in this compilation has the same name, so the error `Conflict: Multiple assets emit to the same filename` throw out. 

Before I do more work to deal with this bug, It worth to discuss a doubt: is it necessary to split independent CSS chunk?

**Comment by borisirota** [comment]
The error `Conflict: Multiple assets emit to the same filename` happens when running `AggressiveSplittingPlugin` without the `extract-text-webpack-plugin` as well.

Happens with the `html-webpack-plugin`. There is a discussion [here](https://github.com/jantimon/html-webpack-plugin/issues/446).

**Comment by hulkish** [comment]
any update on this? seeing this issue also

**Comment by hulkish** [comment]
https://github.com/webpack/webpack/issues/3525

**Comment by hulkish** [comment]
@CntChen Couldn't this be resolve by allowing the `extract-text-webpack-plugin-output-filename` to be the original but prefixed with "extract-text-webpack-plugin-output-filename-"? Ex: `extract-text-webpack-plugin-output-filename-my-unique-file-name.ext`

**Comment by hulkish** [comment]
I solve this by using `"extract-text-webpack-plugin-output-filename-[name]"` for the value of `childCompiler`.

**Comment by amitayr** [comment]
any news with this issue?

**Comment by hulkish** [comment]
@amitayr I wish... seems like we might be out of luck on this one short of finding time to write this fix ourselves

**Comment by alexander-akait** [comment]
DEPRECATED
Please use: https://github.com/webpack-contrib/mini-css-extract-plugin
