### ISSUE TITLE
Option for automatic loading

### ISSUE THREAD

**Issue by rainerhahnekamp** [webpack-contrib/extract-text-webpack-plugin#472]
Please correct me if I am wrong but as I see it, ExtractTextTemplate does not automatically load the generated stylesheet. So in the "normal" way, where I would have:

````javascript
{
  test: /\.css$/,
  use: [{loader: "style-loader"}, {loader: "css-loader"}]
}
````

the css data is loaded automatically. By replacing it with the plugin

````javascript{
  test: /\.css$/,
  use: ExtractTextPlugin.extract({
    fallback: "style-loader",
    loader: "css-loader"
  })
}
````

it generates the css file separately, but I have to manually add

````html
<link href="main.css" rel="stylesheet">
````

to my html file.

In a use case where I am lazy loading multiple "css chunks" this plugin can't be used. Perhaps an option to enable autoload might be helpful.

**Comment by rainerhahnekamp** [comment]
Hello, just wanted to recheck if my issue is unclear or if I could help somehow.

**Comment by ALPIXELMaiki** [comment]
+1

**Comment by michael-ciniawsky** [comment]
@rainerhahnekamp ETWP doesn't support this, it just emits the CSS file, in the first example `style-loader` pitches some JS into the bundle to add the styles to the DOM. For ETWP it is more 'complex' since you need to know the HTML file which isn't normally part of the webpack compilation, but as far as I know `html-webpack-plugin` is extendable and maybe it's possible or already implemented to automatically add the CSS files with it. EWTP's sole propose it to extract the CSS out of the bundle and emit a file, it shouldn't contain any other logic besides that (complex enough)
