### ISSUE TITLE
Rename contentHash -> chunkHash

### ISSUE THREAD

**Issue by hanford** [webpack-contrib/extract-text-webpack-plugin#504]
It's pretty confusing that webpack supports `chunkHash` as the name for hashed chunks, and `extract-text-webpack-plugin` supports `contentHash` as a the name achieving the same thing. 

Took me a couple hours to figure out why some of my hash's weren't updating properly and this ended up being the reason.

Thoughts on renaming this in a future version?

**Comment by juanca** [comment]
Yes. I just ran into a production issue. I was using `chunkhash` (same pattern as `webpack.output.filename`) and any changes were not affecting the hash. 

Would be nice to use similar naming conventions or throwing a warning?

**Comment by damianobarbati** [comment]
any news on this?

**Comment by damianobarbati** [comment]
chunkhash would be very nice

**Comment by evilebottnawi** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/153#issuecomment-225017219

**Comment by schmuli** [comment]
@evilebottnawi 

While it is true that these are different, however:

1. The difference didn't stick out so well, since they are so similarly named, and it took reading the README and comparing it with the Webpack docs, in order to notice the difference and how it affects the build

2. The difference is unexpected, since the meaning of both `chunkhash` and `contenthash` are basically the same, it is the hash of the contents, so the only real difference is that `contenthash` is of the hash of the **extracted** contents

Ideally, you would either rename to `chunkhash` but overwrite with the value of your `contenthash`, or you could validate that the `chunkhash` placeholder is not used in the filename passed to this plugin.
