### ISSUE TITLE
Peer Dependency Webpack 3 

### ISSUE THREAD

**Issue by dsslimshaddy** [webpack-contrib/extract-text-webpack-plugin#567]
Peer is outdated

**Comment by rpoitras** [comment]
I've hit this at work with `npm@3.10.3` which throws the error: 

> extract-text-webpack-plugin@2.1.2 requires a peer of webpack@^2.2.0 but none was installed.

At home with `yarn@027.5` no complaints.

**Comment by dsslimshaddy** [comment]
happens with yarn too [yarn](http://i.imgur.com/PNeXUqU.png)

**Comment by michael-ciniawsky** [comment]
For `webpack v3.0.0`  usage the plugin is currently in beta `npm i -D extract-text-webpack-plugin@beta`.  ⚠️  ETWP `<= v2.0.0`  doesn't work correctly with webpack `v3.0.0`

**Comment by andywer** [comment]
I think this issue is still relevant.

Versions 2.x of extract-text-plugin have a webpack v2 peer dependency and version 3.0 requires webpack v3. But as far as I can see extract-text v2 is also compatible with webpack v3.

Would make perfect sense to add webpack v3 as a potential candidate in the extract-text-plugin@2.x peer dependencies.

That actually has an impact on us: andywer/webpack-blocks#190

**Comment by michael-ciniawsky** [comment]
To my knowledge `extract-text-webpack-plugin =< v2.0.0` isn't compatible with `webpack >= v3.0.0`, since there was a breaking change how modules get stored within a chunk `{Array} => {Set}` in `webpack v3.0.0` and therefore the API changed aswell `chunk.modules.forEach(cb) => chunk.forEachModule(cb)`.

**Comment by AnimaMundi** [comment]
Nobody is talking about versions =< 2.0.0, they are referring to the current version 2.1.2 which as far as my own usage goes, does work with Webpack 3. So the peerDependency for version *2.1.2* should be updated to include Webpack 3.

Install extract-text-webpack-plugin@beta fixes the issue for me, but the documentation says this:

````
# for webpack 3
npm install --save-dev extract-text-webpack-plugin
# for webpack 2
npm install --save-dev extract-text-webpack-plugin@2.1.2
# for webpack 1
npm install --save-dev extract-text-webpack-plugin@1.0.1
```

So that should be updated to this:

````
# for webpack 3
npm install --save-dev extract-text-webpack-plugin@beta
# for webpack 2
npm install --save-dev extract-text-webpack-plugin@2.1.2
# for webpack 1
npm install --save-dev extract-text-webpack-plugin@1.0.1
```

**Comment by sapegin** [comment]
@michael-ciniawsky Should we reopen this? Would you accept a PR? If yes to which branch?

**Comment by d3viant0ne** [comment]
@AnimaMundi - We have to think of more than just your usage. There are breaking changes in Webpack > 3 that prevent extract-text 2.x to be used.

The documentation is correct as is @michael-ciniawsky. The `current version of etwp is 3.0.0` & is required for Webpack > 3.0, the peerDependencies are correct & will not be updated in the etwp 2.x major series.

**Comment by AnimaMundi** [comment]
@d3viant0ne Of course, I can understand that. All I was saying is that I wasn't aware of any incompatibilities as did a few others. The main point of confusion here for me is that @michael-ciniawsky kept referring to versions <= 2.0.0 while everyone else was discussing 2.x. If somebody explicitly mentioned an incompatibility for 2.x with Webpack 3 (as you just did) then that would have cleared things up. The documentation was incorrect at the time of writing while version 3.x was still in beta.
