### ISSUE TITLE
chunk.sortModules is not a function while upgrading application from webpack 2 to webpack 3.0.0

### ISSUE THREAD

**Issue by ayush-srtv** [webpack-contrib/extract-text-webpack-plugin#629]
Hi,
I am upgrading my application from webpack 2.0 to webpack 3.0, i am getting error chunks.sortModules is not a function from extract-text-webpack-plugin. Here is the stackTrace
![image](https://user-images.githubusercontent.com/9304620/30629328-e52a6042-9df8-11e7-8b1c-61f3e7c6bfa1.png)
I have upgraded my webpack version to 3.6.0
![image](https://user-images.githubusercontent.com/9304620/30629365-0450793e-9df9-11e7-85ba-5000deb0b497.png)
and extract-text-webpack-plugin version to 3.0.0.
![webpack-issue-2](https://user-images.githubusercontent.com/9304620/30629406-3e3d6ee0-9df9-11e7-9195-e47a3da6e4b5.JPG)

**Comment by evilebottnawi** [comment]
@ayush-srtv tru to remove `package.lock`, `node-modules` and `npm cache clean` and install again, if problem still exists after this action, please create minimum reproducible test repo, thanks you!

**Comment by kostasmanionis** [comment]
Seems like you have `webpack` installed globally, but your package has another version in `node_modules`, best to inspect that.

**Comment by ayush-srtv** [comment]
I was able to fix the issue somehow. Thanks for the help.

**Comment by this-miguel** [comment]
@ayush-srtv  can you share what you did for solving the problem?

**Comment by ayush-srtv** [comment]
@this-miguel  i did rollback of all the changes in package.json from git and reinstalled webpack v3.6.0  globally then i deleted my node_modules folders and did a `npm i` and somehow it worked, but currently my application is using latest of the 2nd major version of extract-text-webpack-plugin "^2.0.0-beta.5" and if i upgrade extract-text-webpack-plugin to 3.0.0 i still get the same error.

**Comment by this-miguel** [comment]
@ayush-srtv I did manage to solve the problem, for me it was a problem in the packages I used for react, I had updated react to version 16, and I was mixing some packages that were incompatible. The error had nothing to do with webpack actually. For example you should use the version packages in the image, but you should not mix the red ones with the green ones, because some are incompatible, for me it was the version of ` "react": "^16.0.0"` in the red group with the `"react-test-renderer": "^15.6.1"` in the green group. Take a look at your package.json to make sure you are not mixing those:
![screenshot from 2017-10-01 03-10-59](https://user-images.githubusercontent.com/15721544/31052591-c0d623e6-a656-11e7-9e23-d2e460582d62.png)
