### ISSUE TITLE
generate both a normal css and a .min.css file

### ISSUE THREAD

**Issue by stepet80** [webpack-contrib/extract-text-webpack-plugin#637]
Is it possible to use ExtractTextPlugin to create both a normal unminified file and a minified file?
The reason I ask is that I am using a plugin called 'unminified-webpack-plugin' which creates both normal js files and min.js files without having to call webpack twice.

This plugin doesn't work for extract-text-plugin.

**Comment by michael-ciniawsky** [comment]
Minification is not the responsibility of `extract-text-webpack-plugin` itself as it 'only' extracts the CSS chunks and pushed the them to `stats.compilation.assets['[name].css']`, Additional Plugins like e.g [CSSO Plugin](https://www.npmjs.com/package/csso-webpack-plugin) pick up these assets and minify them. Maybe keeping the originals is supported or an opt-in, otherwise open an issue/fork and send PR to e.g `csso-webpack-plugin` to support it :)
