### ISSUE TITLE
extract-text-webpack-plugin with Typescript file and having styleUrls not working

### ISSUE THREAD

**Issue by brijesh-1111** [webpack-contrib/extract-text-webpack-plugin#666]
Hi Team,

I have the latest package installed (angular + webpack + typescript + extract-text-webpack-plugin).
when I compile the ts file using webpack it all come as expected in app.js and I am able to use the final output. 

The issue i am facing is with CSS. in Home.component.ts I have provided the  styleUrls: ['./home.component.css'],
and no where else I have added Require or import statement as I think this itself suffices that thing.

Now in Webpack.config.js I have added the rules with use: ExtractTextPlugin.extract({}) and Plugins for that.

Still I am not getting the CSS file separately. 
Can anyone help me to understand what the silly mistake I am doing?

 check this below image. What I am getting when i run the final output file.
![2017-11-20_181940](https://user-images.githubusercontent.com/25770825/33019240-80fe3a9c-ce1f-11e7-9fc3-7b42d606436a.jpg)

My git repository is: https://github.com/brijesh-1111/Blogger.Web
Here I have added all files for this project

"extract-text-webpack-plugin": "3.0.2",
"webpack": "3.8.1",
 "style-loader": "0.19.0",
"css-loader": "0.28.7",

**Comment by Shub1427** [comment]
I am facing similar issue, but my Compilation fails, when I enable ExtractTextPlugin, with AOT Compilation using @ngtools/webpack, for Angular v4.4.4. 

Though for a webpack.dev.config, the Compilation goes fine... But still the App doesn't run on Browser, gives `Uncaught Error: Expected 'styles' to be an array of strings.`

I thought this might be due to not adding `loader: 'to-string-loader'`, but that was not the issue...

My COnf:

```js
{  
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      { loader: 'to-string-loader' }, 
      { loader: 'css-loader' },
      { loader: 'postcss-loader' },
      { 
        loader: 'sass-loader',
        options: {
          sourceMap: true
        }
      }
    ]
  })
} 
```

**Comment by michael-ciniawsky** [comment]
@Shub1427 Remove `to-string-loader` from your config when using ETWP. I'm not using Angular myself so I'm not 💯 how this exactly works, but if you pass the styles to the angular component/bootstrap ETPW doesn't work (you simply get an CSS file to include via `<link href="">`), so if you pass the CSS `{String}` to angular remove ETWP and  use this part of your current config 'standalone'

```js
use: [
 { loader: 'to-string-loader' }, 
 { loader: 'css-loader' },
 { loader: 'postcss-loader' },
 { loader: 'sass-loader' }
]
```

**Comment by AntonioRedondo** [comment]
Hi @michael-ciniawsky and @d3viant0ne. Great job with this plug-in! Is there any plans to support CSS coming from Angular `@Component`s?

Wouldn't be possible to add a config parameter of the style `exportEmptyString: true` so that this would make modules exporting an empty string rather than removing the content of the function? Like this Angular wouldn't complain about [`Error: Expected 'styles' to be an array of strings`](https://github.com/angular/angular/blob/master/packages/compiler/src/assertions.ts) and `extract-text-webpack-plugin` would work with Angular.

```JavaScript
{  
  test: /\.scss$/,
  use: ExtractTextPlugin.extract({
    exportEmptyString: true
    fallback: 'style-loader',
    use: [
      { loader: 'to-string-loader' }, 
      ...
    ]
  })
} 
```

Th `exportEmptyString` parameter would be used in this `if`:
https://github.com/webpack-contrib/extract-text-webpack-plugin/blob/d5a1de21a65532f66b05a1f6c2146574ce385567/src/loader.js#L33
