### ISSUE TITLE
publicPath not working at all

### ISSUE THREAD

**Issue by zigang93** [webpack-contrib/extract-text-webpack-plugin#693]
I was trying to solve the css output background url issue with publicPath 
but seem like not working at all.

npm devDependencies version : 
```
"devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "clean-webpack-plugin": "^0.1.17",
    "css-loader": "^0.28.7",
    "export-loader": "^1.0.52",
    "exports-loader": "^0.6.4",
    "expose-loader": "^0.7.4",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.6",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "^3.4.0",
    "node-sass": "^4.7.2",
    "pug": "^2.0.0-rc.4",
    "pug-loader": "^2.3.0",
    "resolve-url-loader": "^2.2.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.1",
    "url-loader": "^0.6.2",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7"
  }
```

```
{
    test: /\.scss$/,
    use: extractSass.extract({
        
        use: [
            {
                loader: "css-loader",
                options: {
                    minimize: true,
                }
            },
            {
                loader: "resolve-url-loader"
            },
            {
                loader: "sass-loader",
                options: {
                    sourceMap: true
                }
            }
        ],                 
        fallback: "style-loader",
        publicPath: "../"
        
    })
},
```

**Problem**
css background show: url("img/asset.png")

**What i want** 
css background show: url("../img/asset.png")

**Comment by evilebottnawi** [comment]
@zigang93 seems problem in `resolve-url-loader` because `extract-text-webpack-plugin` don't handle `css` declarations (i.e. `background/src/etc`) it is do `style-loader/css-loader/resolve-url-loader`. We just pass you publicPath to child compilation. Can you disable `extract-text-webpack-plugin` and check url in css?

**Comment by rikedia** [comment]
I have the same problem, when I disable ExtractTextPlugin:
`const extractStyles = new ExtractTextPlugin({
    disable: true,
    ...
})` 
images are found.

When enabled images required from css (scss) files aren't found (HTTP 404).
It is requesting images at `http://localhost:3333/dashboard/img/dashboard/header/default_header_image.jpg` instead of `http://localhost:3333/dashboard/static/src/img/dashboard/header/default_header_image.jpg`

When changing the ExtractTextPlugin publicPath, images are still not found and request are made to the same (faulty) url.

`extractStyles.extract({
    publicPath: "./static/src/",
    ...
});`

My webpack configuration output.publicPath is set to "./static".

**Comment by zigang93** [comment]
Hi.. I solved my problem with  delete my config `file-loader` of `publicPath`. 
`fileloader` overwrite my `publicPath`.
for those facing `publicPath` in `ExtractTextPlugin` not working , please check your other  `publicPath` setting

sorry, my mistake. finally understand how webpack work ..
