### ISSUE TITLE
[webpack@4] Unexpected token: punc ({) on production build

### ISSUE THREAD

**Issue by JounQin** [webpack-contrib/extract-text-webpack-plugin#736]
Reproduction: https://github.com/JounQin/ng-rubick/blob/master/build/webpack.config.ts#L118
Step: enable ExtractTextWebpackPlugin, then run `yarn build`

And also, when ExtractTextWebpackPlugin is disabled, there is en empty app.*.js file generated, you can change https://github.com/JounQin/ng-rubick/blob/master/build/webpack.config.ts#L83-L86 to `use: ['style-loader', ...cssLoaders],` then run `yarn build` to review correct output files.

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
