### ISSUE TITLE
[Webpack 4] Wrong order of entries when using less-loader and @import

### ISSUE THREAD

**Issue by garygreen** [webpack-contrib/extract-text-webpack-plugin#737]
## Example

![image](https://user-images.githubusercontent.com/1702638/36913463-f3da8f6c-1e41-11e8-9f2d-86a54f9ec25a.png)

As you can see, there are two entry points:

```javascript
var webpack = require('webpack');
var path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = {

    entry: {
        site: [
            './bootstrap.less',
            './app.less',
        ]
    },

    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'js/[name].js',
    },

   module: {
       rules: [
       {
           test: /\.less$/,
           use: ExtractTextPlugin.extract({
               use: ['css-loader', 'less-loader'],
               fallback: 'style-loader'
           })
       }
       ]
     },

    plugins: [
       new ExtractTextPlugin('css/[name].css')
    ]

};
```

The `bootstrap.less` uses `@import` to import various bootstrap components (in this case, `bootstrap-badge.less`).

## Result

```css
.app-badge {
  color: yellow;
}
.bootstrap-badge {
  color: blue;
}
```

## Expected

```css
.bootstrap-badge {
  color: blue;
}
.app-badge {
  color: yellow;
}
```

The `bootstrap.less ` file is the first entry, so whatever is output in that less file should be included first, yet it's added to the end.

It seems like it's getting confused when you use an `@import` inside the less file.

In webpack 3, the order is as expected.

![image](https://user-images.githubusercontent.com/1702638/36914036-ca07804e-1e43-11e8-8790-7b7f21b7ff6a.png)

**Comment by garygreen** [comment]
Just realised - is this a possible problem with `css-loader` instead?

**Comment by garygreen** [comment]
Possibly related to #710 ?

**Comment by Kuzirashi** [comment]
I get the same using:
```
module: {
		rules: [
			// Loader for the stylesheets
      {
        test: /\.(css|sass|scss)$/,
        use: ExtractTextPlugin.extract({
          use: [
            {
              loader: 'css-loader',
              options: {
                minimize: false
              }
            },
            {
              loader: 'resolve-url-loader'
            },
            {
              loader: 'sass-loader'
            }
          ],
          fallback: 'style-loader'
        })
      }
		]
  },
```

The funny thing is when I edit CSS file or file when I import the styles everything is correct then (after reload). :)

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future

**Comment by monochrome-yeh** [comment]
@michael-ciniawsky , however, How to use min-css-extract-plugin to group splited css?
there's no option for spliting chunks.
