### ISSUE TITLE
[4.0.0-beta.0] hangs when using webpack 4

### ISSUE THREAD

**Issue by s524797336** [webpack-contrib/extract-text-webpack-plugin#743]
It hangs even without any css-loader, when i remove ExtractTextPlugin, every thing is ok, when i say hangs it means forever hangs cause i wait all day, and it leave a node process and use cpu 100% when i ctrl+c the process

I need help to how to debug this

**Comment by lpillonel** [comment]
I also experience a similar issue with this version and webpack@4.1.0 :
````
0ms recording
 91% additional asset processing ExtractTextPlugin/data/dms-frontapp/node_modules/webpack/lib/optimize/ConcatenatedModule.js:114
	switch (info.type) {
	             ^

TypeError: Cannot read property 'type' of undefined
    at getFinalName (/data/dms-frontapp/node_modules/webpack/lib/optimize/ConcatenatedModule.js:114:15)
    at ConcatenatedModule.source (/data/dms-frontapp/node_modules/webpack/lib/optimize/ConcatenatedModule.js:953:25)
    at Function.renderExtractedChunk (/data/dms-frontapp/node_modules/extract-text-webpack-plugin/dist/index.js:115:38)
    at ExtractTextPlugin.extractedChunks.forEach.extractedChunk (/data/dms-frontapp/node_modules/extract-text-webpack-plugin/dist/index.js:313:46)
    at Array.forEach (<anonymous>)
    ....
````
If I turn `optimization.concatenateModules` to `false` it is working fine. I don't know if the two issues are related.

**Comment by s524797336** [comment]
I have fixed the problem, in my router file, component is imported as webpack dynamic import like this
`router.js`
```
{
   path: '/',
   component: () => import('xxx')
}
```
And some where in the component `xxx`, because i need get path '/' for link, so i include `router.js` to get it. so some how it's a loop in webpack 4 but webpack 3

**Comment by iMarv** [comment]
+1 having the same issue

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
