### ISSUE TITLE
4.0.0-beta.0 outputs javascript in a css file when using the disable option. 

### ISSUE THREAD

**Issue by hally9k** [webpack-contrib/extract-text-webpack-plugin#750]
When using `webpack@4.1.1` and `webpack-dev-server@3.1.1` the disable and fallback option generates a seemingly random `.css` file full of javascript. It looks like one of the js chunks at a glance but turning off splitChunks doesn't fix it. I have to entirely remove the plugin and the loader when in dev mode to avoid it.
Will try to mock up a quick repro when I have some time.

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
