### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by Lin-Kyle** [webpack-contrib/extract-text-webpack-plugin#751]
"extract-text-webpack-plugin": "^4.0.0-beta.0",

const extractCss = new ExtractTextPlugin('style.css'),
  extractScss = new ExtractTextPlugin('scss.css');

{
        test: /\.css$/,
        use: ExtractTextPlugin.extract({fallback: "style-loader", use: ["css-loader"]})
      }, {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: ['css-loader', 'sass-loader']
        })
      }

Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at a (bootstrap:74)
    at Object../node_modules/.0.28.11@css-loader/index.js!./node_modules/.6.0.7@sass-loader/lib/loader.js!./src/assets/css/style.scss (style.scss:2)
    at a (bootstrap:74)
    at Object../src/assets/css/style.scss (style.scss?1880:2)
    at a (bootstrap:74)
    at Object../src/components/square.jsx (square.jsx:3)
    at a (bootstrap:74)
    at index.jsx:7

I can pack the files normally, but the page is wrong.

**Comment by lili21** [comment]
Pls format your code.

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
