### ISSUE TITLE
 Can't resolve 'module'  ‘fs’

### ISSUE THREAD

**Issue by 961771834** [webpack-contrib/extract-text-webpack-plugin#754]
I updated my webpack version to v4.1.1 node v9.5.0 ,but I encounter a problem that current extract-text-webpack-plugin does not resolve 'module'  'fs'.

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issues with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future
