### ISSUE TITLE
[4.0.0-beta.0] TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by lili21** [webpack-contrib/extract-text-webpack-plugin#755]
Using dynamic import will occur the error.

![image](https://user-images.githubusercontent.com/4456380/37647327-efea072e-2c66-11e8-8256-fce154f29614.png)

[reproduce repo](https://github.com/lili21/webpack4-demo/tree/issue/dynamic-import)

Reproduct Steps
----------------

- checkout to `issue/dynamic-import` branch
- `yarn`
- `yarn start`

**Comment by michael-ciniawsky** [comment]
TL;DR Use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) instead :)

The `webpack >= v4.0.0` 'support' for `extract-text-webpack-plugin` was moved to [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin) as more lightweight approach for `webpack >= v4.0.0` and ETWP entered maintenance mode. We are sorry for the inconvenience here, but ETWP reached a point where maintaining it become too much of a burden and it's not the first time upgrading a major `webpack` version was complicated and cumbersome due to issue with ETWP. The mid-term plan is integrate CSS support directly into `webpack` to avoid this kind of issue in the future

**Comment by dhruvdutt** [comment]
@michael-ciniawsky Can we add a note to the readme of this repo for webpack 4?
LMK if I can help with it.
